name: Twerk Fertilizer
version: 1.0.0
api: 4.0.0
author: Matze
description: Twerk Fertilizer plugin - Made by the PMMLP-Team
main: pmmlp\twerkfertilizer\TwerkFertilizer
mcpe-protocol: [560]
depend:
  - PMMLP